server:
  port: 8090
spring:
  application:
    name: consul-client-consumer
  cloud:
    consul:
      host: 192.168.99.104
      port: 8500
      discovery:
        enabled: true
        server-list-query-tags:
          consul-client: "v0.0.1"
        datacenters:
          consul-client: ["dc-tc"]